config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  mount LibraryDesign::Engine => "/library_design"
  
  get '/' => 'home#index', :as => 'root'
  get 'written-answers' => 'home#index', :as => 'home'
  
  get 'written-answers/answers' => 'answer#index', :as => 'answer_list'
  
  get 'written-answers/written-statements' => 'written_statement#index', :as => 'written_statement_list'
  
  get 'written-answers/answering-bodies' => 'answering_body#index', :as => 'answering_body_list'
  get 'written-answers/answering-bodies/:answering_body' => 'answering_body#show', :as => 'answering_body_show'
  
  get 'written-answers/answering-bodies/:answering_body/answers' => 'answering_body_answer#index', :as => 'answering_body_answer_list'
  
  get 'written-answers/answering-bodies/:answering_body/written-statements' => 'answering_body_written_statement#index', :as => 'answering_body_written_statement_list'
  
  get 'written-answers/meta' => 'meta#index', :as => 'meta_list'
  get 'written-answers/meta/cookies' => 'meta#cookies', :as => 'meta_cookies'
  
  
  
  
  
  
  # No longer linked to.
  get 'written-answers/answers/:answer' => 'answer#show', :as => 'answer_show'
  get 'written-answers/members' => 'member#index', :as => 'member_list'
  
  # An unfortuante duplication of the above.
  # Logs show someone is subscribing to the RSS at:
  # https://written-questions.herokuapp.com/answering-bodies/{answering_body.id}.rss
  # Which we don't want to break.
  get 'answering-bodies/:answering_body' => 'answering_body#show', :as => 'answering_body_show_old_url'
end

app/models/written_statement.rb
# == Schema Information
#
# Table name: written_statements
#
#  id                 :integer          not null, primary key
#  house_name         :string(20)       not null
#  made_on            :date             not null
#  member_role        :string(255)      not null
#  posted_to_bluesky  :boolean          default(FALSE)
#  posted_to_mastodon :boolean          default(FALSE)
#  title              :string(255)      not null
#  uin                :string(20)       not null
#  answering_body_id  :integer          not null
#  member_id          :integer          not null
#
# Foreign Keys
#
#  fk_answering_body  (answering_body_id => answering_bodies.id)
#  fk_member          (member_id => members.id)
#
class WrittenStatement < ApplicationRecord
  
  belongs_to :member
  belongs_to :answering_body
  
  def mastodon_post_text
    post_text = ''
    post_text += self.title + '. ' if self.title
    post_text += 'Statement made by ' + self.member_name + ' ' if self.member_name
    post_text += '(' + self.member_role + ') ' if self.member_role
    post_text += 'on behalf of the ' + self.answering_body_name + ' ' if self.answering_body_name
    post_text += self.url
    post_text
  end
  
  def bluesky_post_text
    post_text = ''
    if self.title
      if self.title.length > 100
        post_text += self.title.truncate( 100 ) + ' '
      else
        post_text += self.title + '. '
      end
    end
    post_text += 'Statement made by ' + self.member_name + ' ' if self.member_name
    post_text += 'on behalf of the ' + self.answering_body_name + ' ' if self.answering_body_name
    post_text += self.url
    post_text
  end
  
  def url
    "https://questions-statements.parliament.uk/written-statements/detail/#{self.made_on}/#{self.uin}"
  end
end

app/controllers/written_statement_controller.rb
class WrittenStatementController < ApplicationController
  
  def index
    @written_statements = WrittenStatement.find_by_sql(
      "
        SELECT ws.*, m.display_name AS member_name, ab.name AS answering_body_name
        FROM written_statements ws, members m, answering_bodies ab
        WHERE ws.member_id = m.id
        AND ws.answering_body_id = ab.id
        ORDER BY ws.made_on DESC
      "
    )
    
    @page_title = 'Written statements'
    @description = 'Written statements.'
    @rss_url = written_statement_list_url( :format => 'rss' )
    @crumb << {label: @page_title, url: nil}
    @section = 'written-statements'
  end
end

app/views/written_statement/_written_statement.html.erb
<li class="list-group-item">
	<%= content_tag( 'h2', link_to( written_statement.title, written_statement.url ) ) %>
	<%= content_tag( 'p', "Made in: House of #{written_statement.house_name}" ) %>
	<%= content_tag( 'p', "Made on: #{written_statement.made_on.strftime( $DATE_DISPLAY_FORMAT )}" ) %>
	<%= content_tag( 'p', "Made by: #{written_statement.member.display_name} as #{written_statement.member_role}" ) %>
	<%= content_tag( 'p', "Made on behalf of: #{link_to( written_statement.answering_body.name, answering_body_show_url( :answering_body => written_statement.answering_body.mnis_id ) ) }".html_safe ) %>
	<%= content_tag( 'p', "UIN: #{written_statement.uin}" ) %>
	<%= content_tag( 'p', "Posted to Mastodon: #{written_statement.posted_to_mastodon}" ) %>
	<%= content_tag( 'p', "Posted to Bluesky: #{written_statement.posted_to_bluesky}" ) %>
</li>

app/views/written_statement/index.html.erb
<%= list_item_count_sentence( 'written statement', @written_statements.size ) %>

<%= render :partial => 'library_design/feeds/feeds' %>

<ol class="unnumbered" role="list">
	<%= render :partial => 'written_statement', :collection => @written_statements %>
</ol>